/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package mainProgramInternal;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import utility.JaringanKeDatabase;

import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asta
 */

public class SubFrameTabelData extends javax.swing.JInternalFrame {

    /**
     * Creates new form SubFrameTabelData
     */
    String sql_selectAll = "select * from mobil";
    public SubFrameTabelData() {
        initComponents();
        tampil_data(sql_selectAll);
        JOptionPane.showMessageDialog(null, "Koneksi Database Berhasil");
    }
    
    private void hapusField(){
        namaPembeliTxt.setText("");
        merekTxt.setText("");
        kotaPembeliTxt.setText("");
        tampil_data(sql_selectAll);
    }
    private String cariAtauHapusData(String stringInfo){
        String sql_Data = "";
        if (namaPembeliTxt.getText().isEmpty() && merekTxt.getText().isEmpty() &&
                kotaPembeliTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Masukan data yang ingin "
                    + stringInfo , "Error", JOptionPane.ERROR_MESSAGE);
            tampil_data(sql_selectAll);
        } else if (namaPembeliTxt.getText().isEmpty() && kotaPembeliTxt.getText().isEmpty()) {
            sql_Data = "FROM mobil WHERE merek LIKE '%"
                    + merekTxt.getText() + "%';";
        } else if (merekTxt.getText().isEmpty() && kotaPembeliTxt.getText().isEmpty()) {
            sql_Data = "FROM mobil WHERE nama LIKE '%"
                    + namaPembeliTxt.getText() + "%';";
        } else if (merekTxt.getText().isEmpty() && namaPembeliTxt.getText().isEmpty()) {
            sql_Data = "FROM mobil WHERE wilayah LIKE '%"
                    + kotaPembeliTxt.getText() + "%';";
        } else if (merekTxt.getText().isEmpty()) {
            sql_Data = "FROM mobil WHERE wilayah LIKE '%"
                    + kotaPembeliTxt.getText() + "%' AND nama LIKE '%"
                    + namaPembeliTxt.getText() +"%';";
        } else if (kotaPembeliTxt.getText().isEmpty()) {
            sql_Data = "FROM mobil WHERE merek LIKE '%"
                    + merekTxt.getText() + "%' AND nama LIKE '%"
                    + namaPembeliTxt.getText() +"%';";
        } else if (namaPembeliTxt.getText().isEmpty()) {
            sql_Data = "FROM mobil WHERE wilayah LIKE '%"
                    + kotaPembeliTxt.getText() + "%' AND merek LIKE '%"
                    + merekTxt.getText() +"%';";
        } else {
            sql_Data = "FROM mobil WHERE nama LIKE '%"
                    + namaPembeliTxt.getText() + "%' AND merek LIKE '%"
                    + merekTxt.getText() + "%' AND wilayah LIKE '%"
                    + kotaPembeliTxt.getText() + "%';";
        }
        return sql_Data;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        buttonHapusPencarian = new javax.swing.JButton();
        kotaPembeliTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaPembeliTxt = new javax.swing.JTextField();
        merekTxt = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        buttonHapusData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        totalMobilTxt = new javax.swing.JTextField();
        totalPenjualanTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalPendapatanBersihTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonKeMenu = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Data Penjualan");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tableData.setBackground(new java.awt.Color(204, 204, 204));
        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Nama Pemesan", "Merek", "Kota", "Tipe", "Model", "Tahun", "Harga", "DP", "Lama Cicilan", "Cicilan/Bulan", "Total Akhir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableData.getTableHeader().setReorderingAllowed(false);
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableData);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonHapusPencarian.setText("Hapus Pencarian");
        buttonHapusPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusPencarianActionPerformed(evt);
            }
        });

        jLabel6.setText("Kota");

        jLabel3.setText("CARI/HAPUS DATA");

        jLabel4.setText("Nama Pemesan");

        jLabel5.setText("Merek");

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        buttonHapusData.setText("Hapus Data");
        buttonHapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kotaPembeliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapusData, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPembeliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(merekTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonHapusPencarian))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCari)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaPembeliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(merekTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonHapusPencarian))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(kotaPembeliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonHapusData))))
                .addGap(14, 14, 14))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totalMobilTxt.setEditable(false);

        totalPenjualanTxt.setEditable(false);

        jLabel1.setText("Jumlah Mobil Terjual");

        jLabel7.setText("Total Pendapatan Bersih");

        totalPendapatanBersihTxt.setEditable(false);

        jLabel2.setText("Total Penjualan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalMobilTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPenjualanTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPendapatanBersihTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalMobilTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPenjualanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPendapatanBersihTxt))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        buttonKeMenu.setText("Ke Menu Utama");
        buttonKeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonKeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonKeMenu)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeMenuActionPerformed
        SubFrameMenuOpsi opt_menu = new SubFrameMenuOpsi();
        opt_menu.setVisible(true);
        this.getDesktopPane().add(opt_menu);
        this.dispose();
    }//GEN-LAST:event_buttonKeMenuActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        DefaultTableModel modelTabel = (DefaultTableModel) tableData.getModel();
        modelTabel.setRowCount(0);
        tampil_data("SELECT * " + cariAtauHapusData("dicari"));
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonHapusPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusPencarianActionPerformed
        hapusField();
    }//GEN-LAST:event_buttonHapusPencarianActionPerformed

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        int baris = tableData.rowAtPoint(evt.getPoint());
        String namaPembeli = tableData.getValueAt(baris, 1).toString();
        String merek = tableData.getValueAt(baris, 2).toString();
        String kotaPembeli = tableData.getValueAt(baris, 3).toString();
        namaPembeliTxt.setText(namaPembeli);
        merekTxt.setText(merek);
        kotaPembeliTxt.setText(kotaPembeli);
        
    }//GEN-LAST:event_tableDataMouseClicked

    private void buttonHapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusDataActionPerformed
        String hapusData = cariAtauHapusData("dihapus");
        if (hapusData.equals("")) {
        } else {
            try {
                int pilihanUser = JOptionPane.showConfirmDialog(null, "Hapus Data ?",
                    "Konfirmasi",JOptionPane.OK_CANCEL_OPTION);
                if (pilihanUser == JOptionPane.OK_OPTION) {
                    String sql_kode = "DELETE " + hapusData;
                    Connection koneksiDb =
                            (Connection) JaringanKeDatabase.koneksiDatabase();
                    PreparedStatement stat_preparedStat = 
                            (PreparedStatement) koneksiDb.prepareStatement(sql_kode);
                    stat_preparedStat.execute();
                    tampil_data(sql_selectAll);
                    hapusField();
                } else {
                    JOptionPane.getRootFrame();
                }
            } catch (HeadlessException | SQLException e){}
        }
    }//GEN-LAST:event_buttonHapusDataActionPerformed

    private void tampil_data(String sql_syntax){
        try {
            Statement stat_Statement = (Statement) JaringanKeDatabase.koneksiDatabase().createStatement();
            ResultSet rs_ResultSet = stat_Statement.executeQuery(sql_syntax);
            DefaultTableModel modelTabel;
            modelTabel = (DefaultTableModel) tableData.getModel();
            modelTabel.getDataVector().removeAllElements();
                long noUrut = 1;
                while(rs_ResultSet.next()){
                    modelTabel.addRow(new Object[] {
                        noUrut++, rs_ResultSet.getString(2), rs_ResultSet.getString(3),
                        rs_ResultSet.getString(4), rs_ResultSet.getString(5),
                        rs_ResultSet.getString(6), rs_ResultSet.getString(7),
                        rs_ResultSet.getString(8), rs_ResultSet.getString(9),
                        rs_ResultSet.getString(10),rs_ResultSet.getString(11),
                        rs_ResultSet.getString(12)
                    });
                long totalPenjualan = 0;
                long totalPendapatanBersih = 0;
                int totalMobil;
                totalMobil = rs_ResultSet.getRow();
                for (int i = 0; i < totalMobil; i++){
                    long totalAkhir = (Long.parseLong((String) modelTabel.getValueAt(i, 11)));
                    long hargaMobil = (Long.parseLong((String) modelTabel.getValueAt(i, 7)));
                    totalPenjualan += totalAkhir;
                    totalPendapatanBersih += (totalAkhir - (hargaMobil * 10 / 100));
                }
                totalMobilTxt.setText(""+totalMobil);
                totalPenjualanTxt.setText(""+totalPenjualan);
                totalPendapatanBersihTxt.setText(""+totalPendapatanBersih);
                }
        } catch (SQLException ex) {
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonHapusData;
    private javax.swing.JButton buttonHapusPencarian;
    private javax.swing.JButton buttonKeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kotaPembeliTxt;
    private javax.swing.JTextField merekTxt;
    private javax.swing.JTextField namaPembeliTxt;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField totalMobilTxt;
    private javax.swing.JTextField totalPendapatanBersihTxt;
    private javax.swing.JTextField totalPenjualanTxt;
    // End of variables declaration//GEN-END:variables
}
